### ISSUE TITLE
Configuring VDE support for WiFi

### ISSUE THREAD

**Issue by rcornwell** [obsolescence/pidp10#10]
On machine with hardware NIC, create a TAP device.

Assume TAP0:

vde_switch --tap tap0 --sock /tmp/vde.ctl --mode 660 --group users -mgmt /tmp/vde.mgmt --mgmtmode 660 --mgmtgroup users --daemon --numports 48

On Pi:
sudo vde_switch -t tap0 -s /tmp/vde.ctl -m 666 -mgmt /tmp/vde.mgnt --mgmtmode 666 --daemon
then run:
dpipe vde_plug /tmp/vde.ctl = ssh <user>@<host with NIC> vde_plug /tmp/vde.ctl

**Comment by obsolescence** [comment]
With hardware NIC, you mean an Ethernet connection instead of Wifi, I think?
I will set up a local network on my boat on Friday when I get back home. Boat-Wide Web, no cabled connection to the outside World alas.

**Comment by larsbrinkhoff** [comment]
We may also want a networking solution for a wifi connected Pi for the case that there is no other computer on the network with a hardware NIC.

**Comment by rcornwell** [comment]
Yes, this can be done with NAT setup. However ISTR a problem with using 10.0.0.0 based networks. I recommend moving the NAT to 176.16.0.0 address. This will keep it out of most home networks which are typically 192.168.0.0 addresses.

**Comment by obsolescence** [comment]
>> We may also want a networking solution for a wifi connected Pi for the case that there is no other computer on the network with a hardware NIC.

Yes - in fact, almost nobody will do networking if it requires an Ethernet cable, it is a high barrier to entry. It's why nobody networks RSX-11 on the PiDP-11, sadly. Some sort of tunneling to a second Pi that is​Ethernet-connected?

**Comment by rcornwell** [comment]
There is no requirement that the other side of the VDE need to be a PC or Laptop. You can run the other half of the switch on a Pi.
