### ISSUE TITLE
install.sh fails cloning rcornwell/pidp10 repo if dir already exists

### ISSUE THREAD

**Issue by Bikeman** [obsolescence/pidp10#12]
If you previously had downloaded the source to the "old" emulator, the git clone will fail with an intimidating "fatal: destination path ... already exists" error. Also the following "rm -r ..." commands will fail likewise because sub-folders "panama5" etc are not found. Perhaps use "rm -rf" here for the entire src subfolder and then clone a fresh copy.

**Comment by obsolescence** [comment]
I followed your suggestion, which fits my primitive script style perfectly :-)
