### ISSUE TITLE
Slow down blinky

### ISSUE THREAD

**Issue by larsbrinkhoff** [obsolescence/pidp10#15]
The blinky sample code rotates very quickly on a Pi 5, so the memory indicators are just flickering.  Here is a version that instead of a fixed delay loop waits for a 60 Hz clock tick by looking for at a bit in the APR device.

```
d 1000 MOVEI 1,777
d 1001 ROT 1,1
d 1002 DATAO PI,1
d 1003 CONSO 0,1000
d 1004 JRST 1003
d 1005 CONO 0,1000
d 1006 JRST 1001
```

**Comment by obsolescence** [comment]
Did I not fix that? Will do as soon as I get back to my PiDP. At the moment, working on a Naked Pi :-(

**Comment by larsbrinkhoff** [comment]
The current ITS "blinky" here: https://github.com/obsolescence/pidp10/blob/master/systems/its/boot.pidp#L134-L141 has a busy wait loop, which depends on the speed of the particular computer.  The code I suggested above uses IO instructions to wait for a 60Hz clock tick.  It's only a suggestion, so use it of not as you see fit.

**Comment by larsbrinkhoff** [comment]
By the way, I updated my tooling to support a SIMH deposit script as input and output.  So you can easily convert a binary program to a SIMH script.

E.g. `dump -Fits -Osimh ts.foo foo.do` will convert the input ts.foo ITS executable to a SIMH script foo.do.
