### ISSUE TITLE
install.sh: wget doesn't replace existing zip archives

### ISSUE THREAD

**Issue by Bikeman** [obsolescence/pidp10#17]
As mentioned in the google groups by another user, using wget to download image archives like this:
`wget -P /opt/pidp10/systems/its https://pidp.net/pidp10-sw/its-system.zip`
will work for the first time only, but after that wget will download the file as `its-system.zip.1` , its-system.zip.2` etc and the install script will then unpack the first download, which is never overwritten. See `man wget` for the rather confusing choices of options to control this behavior ... perhaps removing the old files first or pipeing the download to the destination file works best.

**Comment by obsolescence** [comment]
Correct. Fixed, thanks!
