### ISSUE TITLE
Please make source for Imlac Simulator v4.0-0 available?

### ISSUE THREAD

**Issue by snhirsch** [obsolescence/pidp10#25]
Title says it.  I need to rebuild for a Linux box with older glibc and cannot find the actual sources used.

**Comment by larsbrinkhoff** [comment]
There are two different Imlac emulators.  One was written by @jdersch in C#.  It's possible to build it from https://github.com/jdersch/sImlac, but that's not what comes with the PiDP-10 software.

The second one is part of OpenSIMH.  It can be found here: https://github.com/open-simh/simh/tree/master/imlac

**Comment by snhirsch** [comment]
Not getting too far.  Cmake doesn't work (fails with missing license file??).  A simple make in the root directory produces working versions of everything except Imlac.  What am I missing?

**Comment by bscottm** [comment]
@snhirsch Can you be a bit more explicit about the CMake failure (and on which platform)? I'm the maintainer.

**Comment by snhirsch** [comment]
I don't remember the details, but the one Lars pointed me to worked fine:

https://github.com/open-simh/simh.git

I was attempting to build this project on Ubuntu 18.04.

**Comment by larsbrinkhoff** [comment]
It may be important to get the right SIMH, since there are now many to choose from.  I maintain the Imlac emulator in OpenSIMH.

The sImlac emulator is written in C# so needs additional tooling.  I have built it on Linux with the Mono suite.

**Comment by bscottm** [comment]
@snhirsch:

```shell
$ git clone https://github.com/open-simh/simh.git 
$ cd simh 
$ sh .travis/deps.sh linux 
$ cmake/cmake-builder.sh --flavor ninja --config Release --target imlac 
$ BIN/imlac
```

**Comment by snhirsch** [comment]
Sorry for the late response, Holidays and all...  No joy:

```
hirsch@z87:/net/src/platforms/dec/pdp10/src/simh$ cmake/cmake-builder.sh --flavor ninja --config Release --target imlac
** cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
cmake/cmake-builder.sh: SIMH top-evel directory: /net/src/platforms/dec/pdp10/src/simh
cmake/cmake-builder.sh: Build directory:         /net/src/platforms/dec/pdp10/src/simh/cmake/build-ninja
cmake/cmake-builder.sh: Removing CMakeCache.txt and CMakeFiles
/home/hirsch/.local/bin/cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -S /net/src/platforms/dec/pdp10/src/simh -B /net/src/platforms/dec/pdp10/src/simh/cmake/build-ninja 
-- CMAKE_MODULE_PATH: /net/src/platforms/dec/pdp10/src/simh/cmake;/net/src/platforms/dec/pdp10/src/simh/cmake/installer-customizations
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/net/src/platforms/dec/pdp10/src/simh/cmake/build-ninja/CMakeFiles/CMakeOutput.log".
*** cmake/cmake-builder.sh: Errors detected during environment generation. Exiting.
```

Looks like the 'ninja-build' package needs to be included in the script that installs dependencies.  After I did that it built without error.

**Comment by bscottm** [comment]
> Looks like the 'ninja-build' package needs to be included in the script that installs dependencies. After I did that it built without error.

Always one more thing... the GitHub CI/CD pipeline clearly has it preinstalled, so that's likely why it wasn't in the .travis/deps.sh script. Will add -- thanks for finding this!
