### ISSUE TITLE
Auto start, two suggestions.

### ISSUE THREAD

**Issue by larsbrinkhoff** [obsolescence/pidp10#5]
Two suggestions regarding auto starting the PDP-10 emulator.

1. I have no `.profile` in my home directory, but I do have `.bash_profile`, so the install script failed.  The install script could check for both.  If your shell is bash, I think the latter takes precedence.
2. Maybe there could be an option to auto start the emulator when the system boots.

**Comment by obsolescence** [comment]
I will check for point #1!

On point #2, you mean start the simulator as a service? I don't like that too much. For people new to Linux, that is all just very complex stuff, whilst just starting from .profile (or .bash_profile) is simple to understand and switch off.

Is that sensible to you, or am I missing a point here?
