### ISSUE TITLE
System time on startup off by 2 years

### ISSUE THREAD

**Issue by Bikeman** [obsolescence/pidp10#6]
I was positively surprised that ITS greeted me with the right system time (tho in a different time zone than the one set on the host Raspi, but I guess that is fixed in the OS image), and in a year > 2K (not to be expected for an OS that old), but the date was exactly 2 years off: 2022 instead of 2024. 

I was able to manually set the correct date using :PDSET  and ITS seems happy to be in 2024, apparently it still gets the leap-days right until now. But I wonder if it would be possible to set the correct date from the host OS during boot correctly.

THX

**Comment by obsolescence** [comment]
Oh! It is really 2024 already?  :-)

This is one for Lars Brinkhoff - I will ask him as the ITS expert.
Thank you!

**Comment by larsbrinkhoff** [comment]
That's strange, I would have figured it would either be correct - year and all - or entirely off.  The emulator should pick up the current date from the host and pass it to ITS through the PD clock device: https://github.com/rcornwell/sims/blob/master/PDP10/ka10_pd.c

But there's also an offset involved, that is stored on the disk.  So maybe the disk image needs an update?

CC @rcornwell, what do you think?

**Comment by Bikeman** [comment]
oh yes, the file date of the DRAGON / DRAGON . HOARD  file seems to play a role as a fall-back when time cannot be received from networked buddies at the AI lab. 

https://github.com/PDP-10/its/blob/505ad4864c09df00ca6bd06ab40c2e7b63e48fcd/src/sysen1/netime.128#L196

I guess the PD clock device can only keep track of ticks after the beginning of the calendar year, not the year itself. 

Touching that file with a 2024 date in the disk image would make it easier for the first batch of PiDP-10 users, I guess. Plus updating the manual pages on setting the date manually if it is off. Not sure how to set the timezone correctly, tho...

**Comment by larsbrinkhoff** [comment]
We should probably set up a local Chaosnet time server.

Changing the time zone involves rebilding ITS, i.e. the monitor.  You
edit TZONE in the "IFE MCOND KA" section of the the SYSTEM; CONFIG file.

https://github.com/larsbrinkhoff/its-manual/wiki/Assembling-a-new-ITS
