### ISSUE TITLE
Support for running system on WSL under Windows 11

### ISSUE THREAD

**Issue by GrantMeStrength** [obsolescence/pidp10#7]
Steps:

- Clone the repo, run the install script, and then extract the X86 binaries over the Pi binaries.
- Start the PiDP-10 system with **pcpcontrol start 1**
- **pdpcontrol stat** reports "PiDP-10 is up"

Opening any terminal, e.g. con, tvcon, vt52 will display the terminal but not connect to anything.

Might be due to some quirk of WSL's networking?

**Comment by larsbrinkhoff** [comment]
Yes, all peripheral emulators use networking to connect to the central PDP-10 emulator.  It's done through localhost though, which I would assume should be the easiest, safest network interface.

What happens if you manually type e.g. `telnet localhost 10003`?

**Comment by obsolescence** [comment]
I think you have to install telnet on a Windows machine, it's no longer a standard component.
...Come to think of it, that is also true of Ubuntu. Sudo apt install telnet.
On Windows, there are telnet clients you can download.
