### ISSUE TITLE
Emulator escape character

### ISSUE THREAD

**Issue by larsbrinkhoff** [obsolescence/pidp10#9]
^E is the SIMH default escape character, but it's not ideal for the PDP-10 since ^E is used by EMACS.  It's also a special character in TENEX and TOPS-20.

**Comment by larsbrinkhoff** [comment]
Or... is the SIMH command input separate from the emulated teletype now?  In that case, this can be closed.

**Comment by obsolescence** [comment]
Lars,

>> Or... is the SIMH command input separate from the emulated teletype now? In that case, this can be closed.

It is.

Did you try the pidp10 gihub and the install on the Pi?

**Comment by larsbrinkhoff** [comment]
Yes, my install is straight off this repository.
